In [3]:
import numpy as np
# create a sample matrix
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
# perform SVD
U,S,VT=np.linalg.svd(X)
#choose the number of components to keep
n_components=2
#reconstruct the matrix with reduced dimensions
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("orginal matrix")
print(X)
print("\nReconstructed matrix with reduced dimensions:")
print(X_reconstructed)

orginal matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed matrix with reduced dimensions:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
